window.PRODUCTS = [
  {
    id: "ep-travertin",
    cat: "travertin",
    brand: "ELEMENT PAINT",
    title: "Premium Suyuq Travertin",
    subtitle: "25 kg • American Technology • Royal Finish",
    img: "assets/element_travertin.jpg",
    desc: "Element Paint flagman mahsuloti. Bino fasadlari va ichki zallari uchun tabiiy tog' toshi relyefini beruvchi premium dekorativ suvoq. Yuqori qoplash kuchi, quyosh nurlariga chidamlilik va yuviluvchanlik xususiyatiga ega.",
    specs: [
      ["Qadog'i", "25 kg plastik chelak"],
      ["Sarfi", "12 – 16 m² / chelak"],
      ["Qo'llanishi", "Fasad va ichki devorlar"],
      ["Xususiyati", "Suv o'tkazmaydigan, yuviluvchi, UV-bardoshli"],
      ["Texnologiya", "American Technology (AQSh xomashyosi)"],
    ],
  },
  {
    id: "crown-travertin",
    cat: "travertin",
    brand: "CROWN",
    title: "Suyuq Travertin Crown",
    subtitle: "25 kg • Europa Technology • Estd 2026",
    img: "assets/crown_travertin.jpg",
    desc: "Yevropa standartlari asosida yaratilgan yangi avlod suyuq travertini. Noqulay ob-havo, yomg'ir, qor va issiqqa yuqori bardoshli, mustahkam himoya qatlami yaratadi.",
    specs: [
      ["Qadog'i", "25 kg paqir"],
      ["Sarfi", "12 – 15 m² / chelak"],
      ["Standart", "Europa Technology (Estd 2026 seriyasi)"],
      ["Qo'llanishi", "Fasad va zamonaviy interyerlar"],
      ["Xususiyati", "Elastik struktura, yorilishlarga chidamli"],
    ],
  },
  {
    id: "berlak-travertin",
    cat: "travertin",
    brand: "BERLAK",
    title: "Suyuq Travertin Berlak",
    subtitle: "Futuristic Paint • American Technology",
    img: "assets/berlak_travertin.jpg",
    desc: "Berlak brendining xaridorgir narx va yuqori mustahkamlikni birlashtirgan travertin qoplamasi. Fasad va interyer yuzalarida uzoq yillik ishonchli xizmat ko'rsatadi.",
    specs: [
      ["Qadog'i", "25 kg chelak"],
      ["Sarfi", "13 – 16 m²"],
      ["Tarkibi", "Akril polimer, marmar va travertin granulalari"],
      ["Texnologiya", "American Technology"],
    ],
  },
  {
    id: "berlak-ottocento",
    cat: "travertin",
    brand: "BERLAK",
    title: "Ottocento (Ipak va Baxmal)",
    subtitle: "Dekorativ bo'yoq • Italian Luxury Style",
    img: "assets/ottocento.jpg",
    desc: "Devorlarda nafis ipak va baxmal jilosini hosil qiluvchi Italiyancha dekorativ bo'yoq. Xonaga hashamat, mayin yorug'lik o'yini va zamonaviy ko'rk bag'ishlaydi.",
    specs: [
      ["Effekti", "Ipak va baxmal (Ottocento velvet)"],
      ["Rang kodi", "Br-03 Sand / Safio va boshqa palitralar"],
      ["Qo'llanishi", "Mehmonxona, yotoqxona, ofis, restoran"],
      ["Tozalanishi", "Nam mato bilan oson tozalanadi"],
    ],
  },
  {
    id: "ep-plaster",
    cat: "travertin",
    brand: "ELEMENT PAINT",
    title: "Dekor Element Plaster",
    subtitle: "Dekorativ suvoq • Ichki va tashqi ishlar",
    img: "assets/element_plaster.jpg",
    desc: "Devorlardagi mayda notekisliklarni tekislovchi va estetik teksturali relyef yaratuvchi professional dekorativ suvoq.",
    specs: [
      ["Qadog'i", "Standart chelak"],
      ["Qo'llanishi", "Ichki va tashqi barcha devor yuzalari"],
      ["Texnologiya", "Element Standart"],
    ],
  },
  {
    id: "berlak-wallpaper",
    cat: "travertin",
    brand: "BERLAK",
    title: "Suyuq Gul Qog'oz (Fantasy)",
    subtitle: "3 kg • 9-12 m² • Eko-toza Ipak qoplama",
    img: "assets/liquid_wallpaper.jpg",
    desc: "Tabiiy ipak va paxta tolalaridan tarkib topgan ekologik toza suyuq oboy. Choksiz surtiladi, xonada qo'shimcha issiqlik va tovush izolyatsiyasini ta'minlaydi.",
    specs: [
      ["Og'irligi", "3 kg qop"],
      ["Maydoni", "9 – 12 m² qoplaydi"],
      ["Xususiyati", "Ekologik xavfsiz, hidsiz, choksiz sirt"],
      ["Qo'llanishi", "Yotoqxona, bolalar xonasi va zallar"],
    ],
  },
  {
    id: "atlas-blue",
    cat: "emal",
    brand: "ATLAS",
    title: "PF-115 Blue (Havo rang)",
    subtitle: "Yaltiroq alkid emal • Life in Color",
    img: "assets/enamel_blue.jpg",
    desc: "Tashqi va ichki metall, yog'och va beton konstruksiyalar uchun yorqin havo rangdagi chidamli alkid emal.",
    specs: [
      ["Markasi", "PF-115 Glossy"],
      ["Rangi", "Blue (Musaffo havo rang)"],
      ["Quritish vaqti", "24 soat (20°C da)"],
      ["Qo'llanishi", "Darvozalar, panjaralar, derazalar, metall"],
    ],
  },
  {
    id: "atlas-yellow",
    cat: "emal",
    brand: "ATLAS",
    title: "PF-115 Yellow (Sariq)",
    subtitle: "Yorqin quyosh rangi • Yuqori yopuvchanlik",
    img: "assets/enamel_yellow.jpg",
    desc: "Yorqin sariq rangli mustahkam universal emal. Quyosh nurlari ta'sirida rangini yo'qotmaydi, metallni zanglashdan asraydi.",
    specs: [
      ["Markasi", "PF-115 Glossy"],
      ["Rangi", "Sariq (Yellow)"],
      ["Texnologiya", "American Technology"],
      ["Qo'llanishi", "Ichki va tashqi bezash ishlari"],
    ],
  },
  {
    id: "atlas-brown",
    cat: "emal",
    brand: "ATLAS",
    title: "PF-115 Chocolate Brown",
    subtitle: "Shokolad jigar rang • Hashamatli jilo",
    img: "assets/enamel_brown.jpg",
    desc: "To'q va olijanob shokolad jigar rangdagi yaltiroq emal. Yog'och to'siqlar, darvozalar va furnituralarga o'zgacha ko'rkamlik baxsh etadi.",
    specs: [
      ["Markasi", "PF-115 Glossy"],
      ["Rangi", "Chocolate Brown (Shokolad)"],
      ["Chidamlilik", "Namlik va mexanik ta'sirlarga yuqori bardoshli"],
    ],
  },
  {
    id: "atlas-white",
    cat: "emal",
    brand: "ATLAS",
    title: "Emal Standart Oq",
    subtitle: "Yaltiroq oq alkid emal • American texnology",
    img: "assets/enamel_white.jpg",
    desc: "Atlas milliy bo'yog'ining klassik oq rangli yaltiroq alkid emali. Ichki va tashqi yuzalar, metall va yog'och konstruksiyalar uchun mustahkam va estetik qoplama.",
    specs: [
      ["Markasi", "Emal Standart Glossy"],
      ["Rangi", "White / Белая / Oq"],
      ["Texnologiya", "American texnology"],
      ["Qo'llanishi", "Metall, yog'och, deraza va panjaralar"],
    ],
  },
  {
    id: "berlak-white",
    cat: "emal",
    brand: "BERLAK",
    title: "Snow White (Qordek oq emal)",
    subtitle: "Sarg'aymaydigan formula • American Technology",
    img: "assets/enamel_berlak.jpg",
    desc: "Vaqt o'tishi bilan sarg'aymaydigan, qordek oppoq yaltiroq alkid emal. Deraza romlari, eshiklar va ichki metall buyumlar uchun ideal yechim.",
    specs: [
      ["Rangi", "Snow White (Oppog' oq)"],
      ["Jilosi", "Super yaltiroq (High Gloss)"],
      ["Qo'llanishi", "Metall, yog'och, devor"],
    ],
  },
  {
    id: "berlak-floor",
    cat: "emal",
    brand: "BERLAK",
    title: "Pol Emali Berlak",
    subtitle: "Yeyilishga va qirilishga o'ta chidamli",
    img: "assets/enamel_floor.jpg",
    desc: "Yog'och va beton pol yuzalari uchun mo'ljallangan maxsus mustahkamlangan pol bo'yog'i. Harakat bosimi va tez-tez yuvishga bardoshli.",
    specs: [
      ["Turi", "Pol emali (Oltin rang / Qizil-jigar)"],
      ["Qo'llanishi", "Yog'och pollar, zinapoyalar"],
      ["Xususiyati", "Yeyilishga chidamli mustahkam qatlam"],
    ],
  },
  {
    id: "berlak-pearl",
    cat: "lak",
    brand: "BERLAK",
    title: "Marvarid Effektli Lak",
    subtitle: "Gidrofob himoya • Marvarid tovlanishi",
    img: "assets/marvarid.jpg",
    desc: "Travertin va dekorativ bo'yoqlar ustidan surtiluvchi marvarid jilosiga ega himoya laki. Sirtni suv, loy va dog'lardan ishonchli asraydi.",
    specs: [
      ["Effekti", "Marvarid (Pearl) yaltiroqligi"],
      ["Himoya", "Namlik, kir va dog' o'tkazmaydi"],
      ["Qo'llanishi", "Ottocento, travertin, dekorativ devorlar"],
    ],
  },
  {
    id: "berlak-travertin-lak",
    cat: "lak",
    brand: "BERLAK",
    title: "Travertin uchun Maxsus Lak",
    subtitle: "Fasad himoyasi • Shaffof suv o'tkazmas",
    img: "assets/lak_travertin.jpg",
    desc: "Fasad travertinining xizmat muddatini bir necha barobarga uzaytiruvchi shaffof mustahkamlovchi lak. Yog'ingarchilik va sovuqdan to'liq himoya qiladi.",
    specs: [
      ["Turi", "Akril shaffof lak"],
      ["Qo'llanishi", "Fasad travertini, g'isht, tabiiy tosh"],
      ["Texnologiya", "American Technology"],
    ],
  },
  {
    id: "atlas-nitro",
    cat: "lak",
    brand: "ATLAS",
    title: "Nitro Lak НЦ-2144",
    subtitle: "15-20 daqiqada tez quriydi • Shaffof",
    img: "assets/nitro_lak.jpg",
    desc: "Yog'och va mebellar uchun o'ta tez quriydigan shaffof nitro lak. Yog'och tolalarini go'zal bo'rttirib ko'rsatadi.",
    specs: [
      ["Markasi", "НЦ-2144 Nitro lak"],
      ["Qurish vaqti", "15 – 20 daqiqa!"],
      ["Qo'llanishi", "Mebel, eshik, yog'och detallar"],
    ],
  },
  {
    id: "atlas-pf283",
    cat: "lak",
    brand: "ATLAS",
    title: "Atlas PF-283 Porloq Lak",
    subtitle: "Alkid asosli yaltiroq qatlam",
    img: "assets/lak_pf283.jpg",
    desc: "Tashqi va ichki yog'och yuzalarni quyosh nuri, yomg'ir va namlikdan himoyalovchi yaltiroq alkid lak.",
    specs: [
      ["Markasi", "ПФ-283"],
      ["Qoplama", "Yaltiroq (Glossy finish)"],
      ["Brend", "Atlas milliy bo'yoq"],
    ],
  },
  {
    id: "berlak-primer-5kg",
    cat: "primer",
    brand: "BERLAK",
    title: "Akril Gruntovka Astar 1/7 (5 kg)",
    subtitle: "Konsentrat 1/7 formula • 5 kg kanistr",
    img: "assets/grounding_5kg.jpg",
    desc: "1 ulush astar va 7 ulush suv nisbatida aralashtiriladigan tejamkor konsentrat gruntovka. Devor changini bog'laydi va bo'yoq sarfini kamaytiradi.",
    specs: [
      ["Hajmi", "5 kg kanistr"],
      ["Nisbat", "1 : 7 (suv bilan aralashtiriladi)"],
      ["Xususiyati", "Chuqur singuvchi, yopishishni 2 barobar oshiradi"],
    ],
  },
  {
    id: "berlak-primer-2kg",
    cat: "primer",
    brand: "BERLAK",
    title: "Grounding Acrylic Astar (2.5 kg)",
    subtitle: "2.5 kg chelak • European Standard",
    img: "assets/grounding.jpg",
    desc: "Yevropa sifati asosida tayyorlangan akril astar. Gipsokarton, beton va suvoqlangan devorlarni bo'yashga mukammal tayyorlaydi.",
    specs: [
      ["Vazni", "2.5 kg chelak"],
      ["Standart", "European Standard"],
      ["Qo'llanishi", "Ichki va tashqi suvoqlar"],
    ],
  },
  {
    id: "atlas-pva",
    cat: "primer",
    brand: "ATLAS",
    title: "Atlas 801 PVA Kley",
    subtitle: "Universal kuchli yopishqoq yelim",
    img: "assets/pva.jpg",
    desc: "Mebel, yog'och detallari, qog'oz va qurilish qorishmalarining mustahkamligini oshirish uchun universal yuqori yopishqoq PVA yelimi.",
    specs: [
      ["Markasi", "801 PVA"],
      ["Texnologiya", "American Technology"],
      ["Qo'llanishi", "Yog'och, mebel, qurilish qorishmalari"],
    ],
  },
  {
    id: "atlas-glatt",
    cat: "primer",
    brand: "ATLAS",
    title: "Glatt Gips Shpatlyovka",
    subtitle: "Quruq pardoz aralashmasi • Silliq devor",
    img: "assets/glatt.jpg",
    desc: "Ichki xonalarda devor va shiftlarni silliqlash uchun sifatli gipsli shpatlyovka. Oson surtiladi, quriganda yorilmaydi va tekis sirt beradi.",
    specs: [
      ["Turi", "Gipsli pardoz shpatlyovka"],
      ["Brend", "Atlas Glatt"],
      ["Qo'llanishi", "Devor va shiftlarni pardozlash"],
    ],
  },
];
